### ISSUE TITLE
npm start:android error on Windows 10

### ISSUE THREAD

**Issue by hacktember** [clayrisser/reactant#6]
Windows 10 version: 1803
Windows 10 build: 17134.228
NodeJS version: 10.9.0
NPM version: 6.2.0

Screenshot:
![image](https://user-images.githubusercontent.com/41446194/44826305-fd3eca80-abd3-11e8-896e-a8b0486bad49.png)

Debug Log:
[2018-08-30T02_18_05_293Z-debug.log](https://github.com/codejamninja/reaction/files/2334410/2018-08-30T02_18_05_293Z-debug.log)

**Comment by clayrisser** [comment]
Ah, I've not done much testing on windows. Maybe try linux for now. I will def try and test windows better.

**Comment by clayrisser** [comment]
This issue is irrelevant. Reactant has been completely rebuilt from the ground up.
